name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [win-x64, win-x86, linux-x64, linux-arm, linux-arm64, osx-x64]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.101

      - name: Publish
        run: dotnet publish ./Sibusten.Philomena.Downloader.Cmd/Sibusten.Philomena.Downloader.Cmd.csproj -c Release -r ${{matrix.runtime}} --self-contained false -p:PublishSingleFile=true -p:DebugType=None

      - name: Zip
        run: cd ./Sibusten.Philomena.Downloader.Cmd/bin/Release/net5.0/${{matrix.runtime}}/publish && zip -r ~/philomena-downloader-${{matrix.runtime}}.zip ./*

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: philomena-downloader-${{matrix.runtime}}
          path: ~/philomena-downloader-${{matrix.runtime}}.zip
