name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release'
        required: true

jobs:
  publish-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        runtime: [win-x64, win-x86]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.101

      - name: Publish
        run: dotnet publish ./Sibusten.Philomena.Downloader.Cmd/Sibusten.Philomena.Downloader.Cmd.csproj -c Release -r ${{matrix.runtime}} --self-contained false -p:PublishSingleFile=true -p:DebugType=None

      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          dest: philomena-downloader-${{matrix.runtime}}.zip
          files: ./Sibusten.Philomena.Downloader.Cmd/bin/Release/net5.0/${{matrix.runtime}}/publish/
          recursive: false

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: philomena-downloader-${{matrix.runtime}}
          path: philomena-downloader-${{matrix.runtime}}.zip

  publish-nix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [linux-x64, linux-arm, linux-arm64, osx-x64]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.101

      - name: Publish
        run: dotnet publish ./Sibusten.Philomena.Downloader.Cmd/Sibusten.Philomena.Downloader.Cmd.csproj -c Release -r ${{matrix.runtime}} --self-contained false -p:PublishSingleFile=true -p:DebugType=None

      - name: Tar
        uses: thedoctor0/zip-release@0.4.1
        with:
          filename: philomena-downloader-${{matrix.runtime}}.tar.gz
          path: ./Sibusten.Philomena.Downloader.Cmd/bin/Release/net5.0/${{matrix.runtime}}/publish

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: philomena-downloader-${{matrix.runtime}}
          path: philomena-downloader-${{matrix.runtime}}.tar.gz

  create-release:
    runs-on: ubuntu-latest

    needs:
      - publish-windows
      - publish-nix

    steps:
      - uses: actions/checkout@v2

      # Read the changelog section for the release version
      - name: Read changelog entry
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{github.event.inputs.version}}
      
      # Download all binaries
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      
      # DEBUG
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          body: ${{steps.changelog.outputs.changes}}
          draft: true
          prerelease: ${{steps.changelog.outputs.status == 'prereleased'}}
          files: artifacts/**.*
          name: Philomena Downloader v${{github.event.inputs.version}}
          tag_name: v${{github.event.inputs.version}}
